backend/models/Post.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 01.06.15
 * Time: 13:32
 */

namespace backend\models;

class Post extends \common\models\Post
{

    
    // public function getImage()
    // {
    //     return  $this->getImgSrc('postImage'),
          
    // }


}

common/models/Tag.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 19.05.15
 * Time: 13:19
 */

namespace common\models;


class Tag extends \common\models\base\Tag
{
    const DEFAULT_COLOR = 10066329;

    public static function find()
        {
            return new TagQuery(get_called_class());
        }
    
        public static function getByName($name)
        {
            return Tag::findOne(['tagName' => $name]);
        }
    
        public function getUrl()
        {
            return \yii\helpers\Url::to(
                ['post/index', 'term' => $this->tagSlug, 'filter' => 'tag']
            );
        }
    
        public function getName()
        {
            return $this->tagName;
        }
    
        public function getTitle()
        {
            return $this->tagTitle;
        }
    
        public function getSlug()
        {
            return $this->tagSlug;
        }
    
        public function getDescription()
        {
            return $this->tagDescription;
        }

    public function behaviors()
    {
        return [
            'slug' => [
                'class' => 'Zelenin\yii\behaviors\Slug',
                'slugAttribute' => 'tagSlug',
                'attribute' => 'tagName',
                // optional params
                'ensureUnique' => true,
                //'translit' => true,
                'replacement' => '-',
                'lowercase' => true,
                'immutable' => false,
                // If intl extension is enabled, see http://userguide.icu-project.org/transforms/general.
                'transliterateOptions' => 'Russian-Latin/BGN;'
            ]
        ];
    }

}

frontend/models/Post.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 12.05.15
 * Time: 19:12
 */

namespace frontend\models;

use common\models\base\ViewLog;
use common\models\View;
use yii\helpers\Url;

class Post extends \common\models\Post
{
    public function registerView()
    {
        $this->updateCounters(['postViews' => 1]);
    }

    public function registerRawView()
    {
        $this->updateCounters(['postRawViews' => 1]);
    }

    public function getFormatedViews()
    {
        return $this->postRawViews;
        //return number_format($this->postViews, 0, ',', '.');
    }

    public function getFormatedShares()
    {
        return $this->postShare;
        //return number_format($this->postShare, 0, ',', '.');
    }

    public function getMedia()
    {
        if (!empty($this->postVideo)) {
            return \yii\helpers\Html::tag(
                'div',
                $this->postVideo,
                [
                    'class' => 'videoWrapper'
                ]
            );
        }
        return $this->getImage();
    }

    public function getImage()
    {
       $path = str_replace( "postImage/", "postImage/thumb-" , $this->getImgSrc('postImage')) ;
       if(!(@getimagesize($path))){
            $path = $model->getImgSrc('postImage');
        }
        return \yii\helpers\Html::img(
            $path,
            // $this->getImgSrc('postImage'),
            [
                'class' => 'img-responsive',
                'alt' => $this->postTitle
            ]
        );
    }

    public function getUrl($enableAchor = false)
    {
        $data = empty($this->postCanonical) ? [
            'post/view',
            'id' => $this->primaryKey,
            'slug' => $this->postName
        ] : $this->postCanonical;
        return
            Url::to($data, true);
    }

    public function getPre2Raw()
    {
        return preg_replace_callback(
            '#<pre(?:.*?)>(.*?)</pre>#si',
            function ($matches) {
                return html_entity_decode($matches[1]);
            },
            $this->postText
        );
    }

    public function containCodeBlock()
    {
        return preg_match('#<pre(?:.*?)>(.*?)</pre>#si', $this->postText);
    }
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use backend\components\BackendController;
use backend\models\PostSearch;
use common\models\Category;
use common\models\Post;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UnprocessableEntityHttpException;
use yii\web\UnsupportedMediaTypeHttpException;
use darkdrim\simplehtmldom\SimpleHTMLDom;
use yii\imagine\Image;
use Imagine\Gd;
use Imagine\Image\Box;
use Imagine\Image\BoxInterface;
// use Imagine\Exception;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends BackendController
{
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'allow' => true,
                            'roles' => ['admin']
                        ],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
//        if (!\Yii::$app->user->can('admin')) {
//            $searchModel->query = $searchModel->query->andWhere(['userId' => Yii::$app->user->id]);
//        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post(['scenario' => 'create']);
        $model->userId = $model->userId ? $model->userId : Yii::$app->getUser()->id;

        // if 5sfer
        if ($model->userId == 77 && !$model->editorId && Yii::$app->authManager->checkAccess(
                Yii::$app->user->identity->getId(),
                'admin'
            )
        ) {
            $model->editorId = Yii::$app->getUser()->id;
        }
        if ($model->load(Yii::$app->request->post())) {

      
           if ( isset($model->postText) ){
                $pattern = "/(<img.*?src=\".*?)(uploads\/(?!thumb))(.*?\".*?>)/im";
                $replace = "$1uploads/thumb-$3";
                $result = preg_replace($pattern, $replace, $model->postText);
                $result = preg_replace('/alt=".*?"/',"", $result);
                $result = str_replace('<img','<img alt="'.$model->postTitle.'"', $result);
                $model->postText =  $result;
            }

           if($model->save()){
                $model->linkCategories(Yii::$app->request->post('Post')['categories']);
                $model->linkTags(Yii::$app->request->post('Post')['tags']);
                if( isset($model->postImage)){
                      try{
                            $path = "/usr/share/nginx/5sfer/media/post/";
                            // $path = "/home/bigdig/5sfer.bigdig.com.ua/www/media/post/";
                            $filename = $model->postImage;
                            $photo = Image::getImagine()->open($path .$filename);
                            $box = new Box(800,500);
                            $photo->thumbnail($box)->save($path ."thumb-".$filename, ['quality' => 70]);
                     }catch(Exception $e){
                            echo "not valid img! because of: ".$e;
                            continue;
                        }
                }
                $this->alert('Статья создана!');
                return $this->redirect(['update', 'id' => $model->postId]);
           }

        }
        Yii::trace($model->errors);
        return $this->render(
            'create',
            [
                'model' => $model,
            ]
        );

    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (!\Yii::$app->user->can('updatePost', ['post' => $model])) {
            throw new ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
        $model->scenario = 'update';
        if ($model->load(Yii::$app->request->post())) {
            if ( isset($model->postText) ){
                $pattern = "/(<img.*?src=\".*?)(uploads\/(?!thumb))(.*?\".*?>)/im";
                $replace = "$1uploads/thumb-$3";
                $result = preg_replace($pattern, $replace, $model->postText);
                $result = preg_replace('/alt=".*?"/',"", $result);
                $result = str_replace('<img','<img alt="'.$model->postTitle.'"', $result);
                $model->postText =  $result;
            }

            if ( $model->save() ){
                $model->linkCategories(Yii::$app->request->post('Post')['categories']);
                $model->linkTags(Yii::$app->request->post('Post')['tags']);
          
                $this->alert('Изменения сохранены!');


                  if( isset($model->postImage)){
                      try{
                            $path = "/usr/share/nginx/5sfer/media/post/";
                            // $path = "/home/bigdig/5sfer.bigdig.com.ua/www/media/post/";
                            $filename = $model->postImage;
                            $photo = Image::getImagine()->open($path .$filename);
                            $box = new Box(800,500);
                            $photo->thumbnail($box)->save($path ."thumb-".$filename, ['quality' => 70]);
                     }catch(Exception $e){
                            echo "not valid img! because of: ".$e;
                            continue;
                        }
                }
            }
        }

    
        return $this->render(
            'update',
            [
                'model' => $model,
            ]
        );

    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionImageUpload()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        // files storage folder
        $path = Yii::getAlias('@media') . '/uploads/';

        if (!is_dir($path)) {
            mkdir($path, 0755, true);
        }

        // setting file's mysterious name
        $filename = md5(mt_rand()) . '.jpg';
        $file = $path . $filename;

        if (isset($_FILES['file']) && isset($_FILES['file']['tmp_name'])) {
            // copying
            $moved = move_uploaded_file($_FILES['file']['tmp_name'], $file);
    
            // crazy test
            if ($moved && file_exists($file) && filesize($file) > 0) {

                $photo = Image::getImagine()->open($path .$filename);
                $box = new Box(720,505);
                $photo->thumbnail($box)->save($path ."thumb-".$filename, ['quality' => 70]);

                echo shell_exec('convert ' . $file . ' -resize \'720>\' ' . $file . ' >/dev/null 2>/dev/null');
                if (exif_imagetype($file) == IMAGETYPE_JPEG) {
                    echo shell_exec('jpegoptim -p -m80 --strip-all ' . $file . ' >/dev/null 2>/dev/null');
                } elseif (exif_imagetype($file) == IMAGETYPE_PNG . ' >/dev/null 2>/dev/null') {
                    echo shell_exec('optipng ' . $file);
                } else {
                    unlink($file);
                    throw new UnsupportedMediaTypeHttpException("Unrecognized image format");
                }
            } elseif (file_exists($file)) {
                unlink($file);
                throw new UnprocessableEntityHttpException("Empty file recived");
            } else {
                throw new UnprocessableEntityHttpException("Unrecognized upload");
            }

            chmod($file, 0644);

            // displaying file
            $out['filelink'] = '//' . Yii::$app->params['imageHost'] . '/uploads/thumb-' . $filename;
            return $out;
        } else {
            throw new UnprocessableEntityHttpException("Unrecognized upload");
        }

    }

}

frontend/controllers/PostController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 15.05.15
 * Time: 15:06
 */

namespace frontend\controllers;


use common\models\Category;
use common\models\Tag;
use common\models\ViewLog;
use frontend\components\FrontendController;
use frontend\models\Post;
use frontend\models\PostSearch;

class PostController extends FrontendController
{
    public function actionIndex($filter = null, $term = null, $sort = null)
    {
        $searchModel = new PostSearch();
        $searchModel->query = $searchModel->query
            ->with('categories', 'user.profile', 'user.achives')
            ->status(Post::PUBLISH);

        if ($filter == 'tag') {
            $term = Tag::find()->where(['tagSlug' => $term])->one();
            if ($term == false) {
                throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
            }
            $searchModel->query = $searchModel->query->tagFilter($term);
        }

        if ($filter == 'category') {
            $term = Category::find()->where(['categorySlug' => $term])->one();
            if ($term == false) {
                throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
            }
            $searchModel->query = $searchModel->query->categoryFilter($term);
        }

        // на главной в новых статьях показываем только набравшие более 500 просмотров
        if (!$filter && !$sort){
            $searchModel->query = $searchModel->query->minViews(500);
        }

        $dataProvider = $searchModel->search(
            array_merge(
                \Yii::$app->request->queryParams,
                [
                    'filter' => $filter,
                    'term' => $term,
                    'sort' => $sort
                ]
            )
        );

        return $this->render(
            'index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'filter' => $filter,
                'term' => $term,
                'sort' => $sort
            ]
        );
    }

    public function actionView($id, $slug = null)
    {
        $post = Post::findOne($id);
        if ($post != false) {
            if ($post->postName != $slug || !empty($post->postCanonical)) {
                return $this->redirect($post->getUrl(), 301);
            }
            return $this->render(
                'view',
                [
                    'post' => $post
                ]
            );
        } else {
            throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
        }
    }

    public function actionCategory($term = '', $order = null)
    {
        //$posts = Post::last();
        return $this->render(
            'index',
            [
                //'posts' => $posts
            ]
        );
    }

    public function actionStat()
    {
        $headers = \Yii::$app->response->headers;
        $headers->set('X-Accel-Expires', 0);

        $t = \Yii::$app->request->post('t');

        $post = Post::findOne($postId = \Yii::$app->request->get('slug'));

        if (!$post) {
            \Yii::$app->end(200);
        }

        switch (\Yii::$app->request->post('t')) {
            case 'v':
                ViewLog::log($post);
                break;
            case 's':
                if ($count = \Yii::$app->request->post('count', null)) {
                    $post->postShare = $count;
                    $post->save(true, ['postShare']);
                }
                break;
        }

        echo json_encode(
            [
                'v' => $post->postRawViews,
                's' => $post->postShare
            ]
        );

        \Yii::$app->end(200);
    }

    // old point
    public function actionUpdate()
    {
        $postId = \Yii::$app->request->get('slug');

        if ($postId) {
            \Yii::$app->response->redirect(
                \yii\helpers\Url::to(['post/stat', 'slug' => $postId]),
                301
            );
        }
    }
}

backend/views/post/_item.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 03.06.15
 * Time: 17:41
 *
 * @var $model backend\models\Post
 */
?>
<tr>
    <td>
        <div>
            <?php foreach ($model->categories as $cat): ?>
                <span class="small" style="margin-right: 5px">
                        <b><?= $cat->title ?></b>
                    </span>
            <?php endforeach ?>
        </div>
        <div><?= \yii\helpers\Html::a(
                $model->postTitle,
                \yii\helpers\Url::to(['update', 'id' => $model->primaryKey])
            ) ?></div>
    </td>
    <td>
        <?= \yii\helpers\Html::a(
            $model->user->profile->name,
            \yii\helpers\Url::to(['author/update', 'id' => $model->user->profile->user_id])
        ) ?>
    </td>
    <td>
        <span class="label label-<?= 'true' == 'true' ? 'primary' : 'info' ?>">
            <?= $model->postStatus ?>
        </span>
    </td>
    <td>
        <?= $model->postPublishTime ? strftime('%d-%m-%y&nbsp;%H:%M', $model->postPublishTime) : '' ?>
    </td>
</tr>

backend/views/post/_search.php
<?php

use yii\helpers\Html;
use \kartik\form\ActiveForm;
use \kartik\builder\Form;
use \kartik\builder\FormGrid;
use \yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model backend\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<br>
<div class="category-form well">

    <legend>Фильтры</legend>

    <?php

    $form = ActiveForm::begin(
        [
            'type' => ActiveForm::TYPE_VERTICAL,
//            'enableClientValidation' => true,
//            'enableClientScript' => true,
            'action' => ['index'],
            'method' => 'get',
        ]
    );

    $cityDesc = empty($model->userId) ? '' : \common\models\Profile::findOne($model->userId)->name;

    $mainRow = [
        'attributes' => [
            'postId' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => '']],
            'postTitle' => ['type' => Form::INPUT_TEXT, 'options' => ['placeholder' => '']],
            'postStatus' => [
                'type' => Form::INPUT_DROPDOWN_LIST,
                //'draft','approval','future','publish','archive'
                'items' => [
                    '' => 'Все',
                    $model::DRAFT => 'Черновики',
                    $model::APPROVAL => 'Ожидают проверки',
                    $model::FUTURE => 'Запланированные',
                    $model::PUBLISH => 'Опубликованные',
                    $model::ARCHIVE => 'Архивные',
                ],
                'options' => ['placeholder' => 'статус']
            ],
            'categoryId' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\Select2::className(),
                'options' => [
                    'options' => ['placeholder' => 'Категория'],
                    'data' => \yii\helpers\ArrayHelper::map(
                        \common\models\Category::find()->all(),
                        'categoryId',
                        'categoryName'
                    ),
                    'pluginOptions' => [
                        'multiple' => false,
                        'minimumInputLength' => 0,
                    ],
                ]
            ],
            'userId' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => \kartik\widgets\Select2::className(),
                'options' => [
                    'initValueText' => $cityDesc, // set the initial display text
                    'options' => ['placeholder' => 'Выберите ...'],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'minimumInputLength' => 1,
                        'ajax' => [
                            'url' => \yii\helpers\Url::to(['author/authorlist']),
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term}; }')
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('function(city) { return city.text; }'),
                        'templateSelection' => new JsExpression('function (city) { return city.text; }'),
                    ],

                ],
            ]
        ]
    ];

    $actionRow = [
        'attributes' => [
            'actions' => [    // embed raw HTML content
                'type' => Form::INPUT_RAW,
                'value' => Html::submitButton(
                        'Применить',
                        ['class' => 'btn btn-primary']
                    ) .
                    ' ' .
                    Html::a(
                        'Сбросить',
                        \yii\helpers\Url::to(['']),
                        ['class' => 'btn btn-default']
                    )
            ],
        ]
    ];

    echo FormGrid::widget(
        [
            'model' => $model,
            'form' => $form,
            'autoGenerateColumns' => false,
            'rows' => [$mainRow, $actionRow]
        ]
    );

    ActiveForm::end();

    ?>

</div>
<div class="btn-group btn-group-justified sort-ordinal">
    <?= $model->sorter->link('popular', ['class' => 'btn btn-default']) . $model->sorter->link(
        'date',
        ['class' => 'btn btn-default']
    ) ?>
</div>

backend/views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Post */

$this->title = 'Новая статья';
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/post/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Статьи';
$this->params['breadcrumbs'][] = $this->title;

$listLayout = "
            <table class='table'>
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Статус</th>
                    <th style='min-width: 120px'>Время</th>
                </tr>
                </thead>
                <tbody>
                    {items}\n
                </tbody>
            </table>
            {pager}
";
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-8">
            <?= ListView::widget(
                [
                    'layout' => $listLayout,
                    'dataProvider' => $dataProvider,
                    'itemOptions' => ['class' => 'item'],
                    'itemView' => '_item',
                ]
            ) ?>
        </div>
        <div class="col-md-4">
            <p>
                <?= Html::a('Создать статью', ['create'], ['class' => 'btn btn-lg btn-block btn-success']) ?>
            </p>
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>

            <br>
            <p class="text-center">
                для быстрого перехода в админку с фронтенда, перетащите эту кнопку на панель закладок
            </p>
            <p class="text-center">
                <a href='javascript:location.href = location.href.replace("http://5sfer.com/","http://backend.5sfer.com/post/update?id=")'
                   type="button" class="btn btn-info btn-xs" onclick="return false;">
                    <span class="glyphicon glyphicon-pencil"></span> Редактировать статью</a>
            </p>
        </div>
    </div>

</div>

backend/views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Post */

$this->title = $model->isNewRecord ? 'Новая статья' : 'Редактирование статьи';
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="post-update" xmlns="http://www.w3.org/1999/html">

    <h1><?= Html::encode($this->title) ?><?= in_array(
            $model->postStatus,
            [
                \common\models\Post::FUTURE,
                \common\models\Post::PUBLISH
            ]
        ) ? ' <a class="btn btn-info" target="_blank" href="' . Yii::$app->params['frontendBaseUrl'] . '/' . $model->primaryKey . '">просмотреть</a>' : '' ?></h1>

    <?= $this->render(
        '_form',
        [
            'model' => $model,
        ]
    ) ?>

</div>

backend/views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Post */

$this->title = $model->postId;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->postId], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->postId], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'postId',
            'userId',
            'postTitle',
            'postLead:ntext',
            'postText:ntext',
            'postName',
            'postVideo:ntext',
            'postViews',
            'postShare',
            'postUpdateTime:datetime',
            'postPublishTime:datetime',
            'postPopularity',
            'postStatus',
        ],
    ]) ?>

</div>