common/models/Author.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 03.06.15
 * Time: 13:42
 */

namespace common\models;

use himiklab\sitemap\behaviors\SitemapBehavior;

class Author extends User
{
    const WAIT = 'wait';
    const APPROVED = 'approved';
    const REJECTED = 'rejected';
    const STAFF = 'staff';

    public static function find()
    {
        return new AuthorQuery(get_called_class());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosition($dayshift)
    {
        return $this->hasOne(Position::className(), ['user_id' => 'id'])
            ->onCondition('date = DATE_SUB(CURDATE(), INTERVAL :dayshift DAY) AND type = :type')->addParams(
                [':dayshift' => $dayshift]
            );
    }

    public function getUrl()
    {
        return \yii\helpers\Url::to(['author/index', 'slug' => $this->profile->slug]);
    }

    public function getUrlComment()
    {
        return \yii\helpers\Url::to(['author/comment', 'slug' => $this->profile->slug]);
    }

    public function getUrlAchives()
        {
            return \yii\helpers\Url::to(['author/achives', 'slug' => $this->profile->slug]);
        }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosition1()
    {
        return $this->getPosition(1);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosition7()
    {
        return $this->getPosition(7);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosition30()
    {
        return $this->getPosition(30);
    }

    public function getEvents()
    {
        return $this->hasMany(Event::className(), ['userId' => 'id']);
    }

    public function getActiveEvents()
    {
        return $this->hasMany(Event::className(), ['userId' => 'id'])->andWhere(['eventStatus' => 'on'])->andWhere(
            ['>', 'eventDate', time()]
        )->orderBy(['eventDate' => SORT_ASC]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAchives()
    {
        return $this->hasMany(Achive::className(), ['achiveId' => 'achiveId'])->viaTable(
            'user_has_achive',
            ['userId' => 'id']
        );
    }

    public function linkAchives($ids)
    {
        $this->unlinkAll('achives', true);
        if ($ids) {
            foreach (Achive::findAll($ids) as $item) {
                $this->link('achives', $item);
            }
        }
    }

}

backend/controllers/AuthorController.php
<?php

namespace backend\controllers;

use backend\components\BackendController;
use common\models\Author;
use common\models\AuthorSearch;
use kartik\widgets\Growl;
use Yii;
use common\models\User;
use common\models\UserSearch;

use yii\db\Query;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class AuthorController extends BackendController
{
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render(
            'view',
            [
                'model' => $this->findModel($id),
            ]
        );
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = Yii::createObject(
            [
                'class' => \dektrium\user\models\User::className(),
                'scenario' => 'create',
            ]
        );

        if ($model->load(Yii::$app->request->post()) && $model->create()) {

            $auth = Yii::$app->authManager;
            $auth->assign($auth->getRole('author'), $model->primaryKey);

            $this->alert('Пользователь создан');
            return $this->redirect(['update', 'id' => $model->primaryKey]);
        }

        return $this->render(
            'create',
            [
                'model' => $model
            ]
        );

    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';
        if (isset($model->postForm)){
            $model->postForm = str_replace ('<script ', '<script data-cfasync="false"', $model->postForm);
        }
        if ($model->load(Yii::$app->request->post())
            && $model->profile->load(Yii::$app->request->post())
            && $model->profile->validate()
            && $model->save(true, ['username','email','achives'])
            && $model->profile->save()
        ) {
            $model->linkAchives(Yii::$app->request->post('Author')['achives']);
            $this->alert('Изменения сохранены');
        }
        return $this->render(
            'update',
            [
                'model' => $model
            ]
        );

    }

    public function actionBlock($id)
    {
        if ($id == Yii::$app->user->getId()) {
            Yii::$app->getSession()->setFlash('danger', Yii::t('user', 'You can not block your own account'));
        } else {
            $user = $this->findModel($id);
            if ($user->getIsBlocked()) {
                $user->unblock();
            } else {
                $user->block();
            }
        }

        return $this->redirect(Url::previous('actions-redirect'));
    }


    public function actionAuthorlist($q = null, $id = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query();
            $query->select('user_id as id, name AS text')
                ->from('profile')
                ->where(['like', 'profile.name', $q]);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Profile::find($id)->name];
        }
        return $out;
    }

    public function actionEditorlist($q = null, $id = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        $admins = Yii::$app->authManager->getUserIdsByRole('admin');
        if (!is_null($q)) {
            $query = new Query();
            $query->select('user_id as id, name AS text')
                ->from('profile')
                ->where(['like', 'profile.name', $q])
                ->andWhere(['user_id' => $admins]);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Profile::find($id)->name];
        }
        return $out;
    }

}

frontend/controllers/AuthorController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 01.06.15
 * Time: 11:19
 */

namespace frontend\controllers;


use common\models\Author;
use frontend\components\FrontendController;
use frontend\models\Post;
use frontend\models\PostSearch;

class AuthorController extends FrontendController
{

    public function actionIndex($slug = null)
    {
        if (!$slug) {
            return $this->redirect(['top10/']);
        } else {
            $model = Author::find()->joinWith('profile')->where(['profile.slug' => $slug])->one();
            if ($model == false) {
                throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
            }

            $searchModel = new PostSearch();
            $searchModel->query = $searchModel->query
                ->with('categories', 'user.profile')
                ->status(Post::PUBLISH)
                ->author($model->primaryKey);

            $dataProvider = $searchModel->search([]);

            return $this->render(
                'view',
                [
                    'model' => $model,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                ]
            );
        }
    }

    public function actionComment($slug)
    {
        $model = Author::find()->joinWith('profile')->where(['profile.slug' => $slug])->one();
        if ($model == false || $model->profile->triggerComment == 'off') {
            throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
        }

        return $this->render(
            'comment',
            [
                'model' => $model
            ]
        );
    }

    public function actionAchives($slug)
    {
        $model = Author::find()->joinWith('profile')->where(['profile.slug' => $slug])->with('achives')->one();
        if ($model == false || !$model->achives) {
            throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
        }

        return $this->render(
            'achives',
            [
                'model' => $model
            ]
        );
    }

    public function actionFinishSubscribe($slug)
    {
        $model = Author::find()->joinWith('profile')->where(['profile.slug' => $slug])->one();
        if ($model == false) {
            throw new \yii\web\HttpException(404, 'Ой! Нет такой страницы!');
        }

        return $this->render(
            'finish-subscribe',
            [
                'model' => $model
            ]
        );
    }
}

frontend/views/author/_author_list.php
<div class="row">
    <div class="col-md-12 margin-bottom-40">
        <div class="row">
            <div class="col-lg-2 visible-lg">
                <?= $this->render(
                    '/author/_ava',
                    [
                        'model' => $model,
                        'showName' => isset($showName) ? $showName : false,
                        'active' => isset($active) ? $active : false,
                    ]
                ) ?>
            </div>
            <div class="col-md-12 col-lg-10">
                <?= isset($label) ? $label : '' ?>
                <?= isset($h) ? '<' . $h . '>' : '<h2>' ?>
                <?= isset($active) && $active ? \yii\helpers\Html::a(
                    $model->profile->name,
                    $model->url
                ) : $model->profile->name ?>
                <?= isset($h) ? '</' . $h . '>' : '</h2>' ?>

                <p><?= $model->profile->bio ?></p>
                <?php if (isset($links) && $links): ?>
                    <ul class="social-icons">

                        <?php if ($model->profile->facebook): ?>
                            <li><a href="<?= $model->profile->facebook ?>" data-original-title="Facebook"
                                   class="rounded-x social_facebook" target="_blank"></a></li>
                        <?php endif; ?>
                        <?php if ($model->profile->vk): ?>
                            <li><a href="<?= $model->profile->vk ?>" data-original-title="Vk"
                                   class="rounded-x social_vk" target="_blank"></a></li>
                        <?php endif; ?>
                        <?php if ($model->profile->twitter): ?>
                            <li><a href="<?= $model->profile->twitter ?>" data-original-title="Twitter"
                                   class="rounded-x social_twitter" target="_blank"></a></li>
                        <?php endif; ?>
                        <?php if ($model->profile->gplus): ?>
                            <li><a href="<?= $model->profile->gplus ?>"
                                   data-original-title="Goole Plus" class="rounded-x social_googleplus"
                                   target="_blank"></a>
                            </li>
                        <?php endif; ?>
                        <?php if ($model->profile->youtube): ?>
                            <li><a href="<?= $model->profile->youtube ?>" data-original-title="Youtube"
                                   class="rounded-x social_youtube" target="_blank"></a></li>
                        <?php endif; ?>
                        <?php if ($model->profile->website): ?>
                            <li><a href="<?= $model->profile->website ?>" data-original-title="Rss"
                                   class="rounded-x social_rss" target="_blank"></a></li>
                        <?php endif; ?>
                    </ul>
                <?php endif ?>
                <?php if (isset($events) && $events && count($model->activeEvents) > 0): ?>
                    <div class="margin-top-20">
                        <h3><i class="fa fa-calendar color-darkgrey"></i> Ближайшие события</h3>
                    </div>
                    <div class="event-list">
                        <ul class="list-unstyled">
                            <?php foreach ($model->activeEvents as $event): ?>
                                <li>
                                    <small><?= strftime('%d.%m', $event->eventDate) ?></small>
                                    - <a href="<?= $event->eventUrl ?>" target="_blank"> <?= $event->eventName ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

frontend/views/author/_ava.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 10.06.15
 * Time: 17:56
 *
 *  Блок с аватарой именем и рейтингом автора
 */
?>

<div class="row<?= isset($class) ? ' ' . $class : '' ?>">
    <div class="col-sm-11 col-xs-2 margin-bottom-5 text-center">
        <?php if (isset($active) && $active && $model->achives): ?>
            <a data-toggle="tooltip" data-placement="top"
               title="Достижения: «<?= $model->achives[0]->achiveTitle ?>»<?= count(
                   $model->achives
               ) == 1 ? '' : ' и еще ' . (count($model->achives) - 1) ?>" class="author-achives dodgerblue-tooltip"
               href="<?= $model->urlAchives ?>">
                <i class="fa fa-star color-orange"></i>
            </a>
            <?php
            $this->registerJs(
                "$('[data-toggle=\"tooltip\"]').tooltip();"
            );
            ?>
        <?php endif; ?>
        <?php if (isset($active) && $active): ?>
        <a href="<?= $model->url ?>">
            <?php endif ?>
            <?= $model->profile->getImgHtml(
                'avatar',
                0,
                false,
                [
                    'class' => "img-responsive rounded-x",
                    'alt' => $model->profile->name
                ]
            ) ?>
            <?php if (isset($active) && $active): ?>
        </a>
    <?php endif ?>
    </div>
    <?php if (isset($showName) && $showName): ?>
        <div class="col-sm-11 col-xs-2 text-center margin-bottom-5">
            <div class="overflow-h">
                <?php if (isset($active) && $active): ?>
                <a class="author-name" href="<?= $model->url ?>">
                    <?php endif ?>
                    <span class="author-name">
                            <?= $model->profile->name ?>
                    </span>
                    <?php if (isset($active) && $active): ?>
                </a>
            <?php endif ?>
            </div>
        </div>
    <?php endif ?>
</div>

frontend/views/author/_datalayer.php
<?php

if (isset($model)) {
    $data = [
        'author' => $model->profile->name,
    ];

    echo \frontend\widgets\DataLayer\DataLayerWidget::widget(['data' => $data]);
}

frontend/views/author/_post_thumb.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 14.05.15
 * Time: 15:34
 *
 * @var $model frontend\models\Post
 */
setlocale(LC_TIME, "");
setlocale(LC_TIME, 'ru_RU.UTF-8', 'Russian_Russia', 'Russian');
?>

<time class="cbp_tmtime">
    <span>
        <small>
            <i class="fa fa-eye margin-right-10"> <?= $model->getFormatedViews() ?></i>
            <i class="fa fa-share-alt"> <?= $model->postShare ?></i>
        </small>
    </span>
    <span>
        <div><?= strftime("%B, %e", $model->postPublishTime) ?>
        </div>
        <div><?= strftime(
                "%G",
                $model->postPublishTime
            ) ?>
        </div>
    </span>
</time>
<i class="cbp_tmicon rounded-x hidden-xs"></i>

<div class="cbp_tmlabel">

    <div class="row">
        <div class="col-md-12">
            <h3><a href="<?= $model->getUrl() ?>"><?= $model->postTitle ?></a></h3>

            <p><?= strip_tags($model->postLead) ?>... </p>
            <a href="<?= $model->getUrl() ?>" class="btn-u btn-u-blue rounded">Читать дальше</a>
        </div>
    </div>
</div>

frontend/views/author/achives.php
<?php


$this->title = 'Достижения эксперта - ' . $model->profile->name . ' - 5 сфер';
$this->registerMetaTag(
    [
        'name' => 'Description',
        'content' => 'Достижения эксперта ' . $model->profile->name . '. ' . $model->profile->bio
    ]
);


Yii::$app->opengraph->title = $model->profile->name;
Yii::$app->opengraph->description = $model->profile->bio;
Yii::$app->opengraph->image = $model->profile->avatar ? Yii::$app->params['frontendBaseUrl'] . '/user/avatar/' . $model->profile->avatar : Yii::$app->params['frontendBaseUrl'] . '/img/5sfer-1200x900.jpg';
Yii::$app->opengraph->twitter->card = 'summary';
Yii::$app->opengraph->twitter->site = '5sfer.com';
if ($this->context->getCanonical()) {
    Yii::$app->opengraph->url = $this->context->getCanonical();
}

$this->params['author'] = $model->profile->name;
?>

<?= $this->render('_author_list', ['model' => $model, 'links' => true, 'events' => true, 'h' => 'h1']) ?>

    <div class="margin-bottom-40 img-center">
        <?= \frontend\widgets\DFP::widget(
            [
                'iu' => '/59738484/author-banner',
                'sz' => [728, 90],
                't' => array_intersect_key($this->params, array_flip(['author']))
            ]
        ); ?>
    </div>

    <div class="margin-bottom-40">
        <span class="head hidden-xs"><h2>От автора</h2></span>
        <ul class="nav nav-tabs _navbar-right">
            <li class="pull-right active">
                <a href="<?= $model->urlAchives ?>"><i class="fa fa-star-o"></i> Достижения</a>
            </li>
            <?php if ($model->profile->triggerComment == 'on'): ?>
                <li class="pull-right">
                    <a href="<?= $model->urlComment ?>"><i class="fa fa-comments-o"></i> Консультации</a>
                </li>
            <?php endif ?>
            <li class="pull-right">
                <a href="<?= $model->url ?>"><i class="fa fa-file-text-o"></i> Публикации</a>
            </li>
        </ul>
    </div>

<?php foreach ($model->achives as $achive): ?>
    <div class="col-xs-12 rounded-2x margin-bottom-40" style="background: #f3f3f3;">
        <div class="row" style="padding: 1px 10px 10px 10px">
            <div class="col-xs-12" style="padding-top: 10px"><h3 style="border-bottom: 1px solid #ddd;padding: 0 0 5px;margin-bottom: 15px;"><?= \yii\helpers\Html::a(
                        $achive->achiveTitle,
                        $achive->achiveUrl,
                        ['target' => '_blank']
                    ) ?></h3></div>
            <div class="col-xs-12 margin-bottom-5">
                <p><?= $achive->achiveDescription ?></p>
            </div>
            <div class="col-xs-12" style="margin: 0px 0px 10px 0px">
                <?= \yii\helpers\Html::a(
                                    'Узнать больше',
                                    $achive->achiveUrl,
                                    ['target' => '_blank', 'class'=>'btn-u btn-u-md btn-u-blue rounded']
                                ) ?>
            </div>
        </div>
    </div>
<?php endforeach ?>

<?php

// extra data begin
$this->render('_datalayer', [
    'model' => $model
]);
// extra data end

frontend/views/author/comment.php
<?php


$this->title = 'Консультирует ' . $model->profile->name . ' - 5 сфер';
$this->registerMetaTag(
    [
        'name' => 'Description',
        'content' => 'Консультации эксперта ' . $model->profile->name . '. ' . $model->profile->bio
    ]
);


Yii::$app->opengraph->title = $model->profile->name;
Yii::$app->opengraph->description = $model->profile->bio;
Yii::$app->opengraph->image = $model->profile->avatar ? Yii::$app->params['frontendBaseUrl'] . '/user/avatar/' . $model->profile->avatar : Yii::$app->params['frontendBaseUrl'] . '/img/5sfer-1200x900.jpg';
Yii::$app->opengraph->twitter->card = 'summary';
Yii::$app->opengraph->twitter->site = '5sfer.com';
if ($this->context->getCanonical()) {
    Yii::$app->opengraph->url = $this->context->getCanonical();
}

$this->params['author'] = $model->profile->name;
?>

<?= $this->render('_author_list', ['model' => $model, 'links' => true, 'events' => true, 'h' => 'h1']) ?>

    <div class="margin-bottom-40 img-center">
        <?= \frontend\widgets\DFP::widget(
            [
                'iu' => '/59738484/author-banner',
                'sz' => [728, 90],
                't' => array_intersect_key($this->params, array_flip(['author']))
            ]
        ); ?>
    </div>

    <div class="margin-bottom-40">
        <span class="head hidden-xs"><h2>От автора</h2></span>
        <ul class="nav nav-tabs _navbar-right">
            <?php if ($model->achives != false): ?>
            <li class="pull-right">
                <a href="<?= $model->urlAchives ?>"><i class="fa fa-star-o"></i> Достижения</a>
            </li>
            <?php endif ?>
            <?php if ($model->profile->triggerComment == 'on'): ?>
                <li class="pull-right active">
                    <a href="<?= $model->urlComment ?>"><i class="fa fa-comments-o"></i> Консультации</a>
                </li>
            <?php endif ?>
            <li class="pull-right">
                <a href="<?= $model->url ?>"><i class="fa fa-file-text-o"></i> Публикации</a>
            </li>
        </ul>
    </div>

    <div>
        <div id="mc-container">
            <div id="mc-content">
                <ul id="cackle-comments">
                </ul>
            </div>
        </div>
        <script type="text/javascript">
            cackle_widget = window.cackle_widget || [];
            cackle_widget.push({
                widget: 'Comment',
                id: '22299',
                url: '<?= $model->urlComment ?>'
            });
            document.getElementById('mc-container').innerHTML = '';
            (function () {
                var mc = document.createElement('script');
                mc.type = 'text/javascript';
                mc.async = true;
                mc.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cackle.me/widget.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(mc, s.nextSibling);
            })();
        </script>

    </div>
<?php

// extra data begin
$this->render('_datalayer', [
    'model' => $model
]);
// extra data end

frontend/views/author/finish-subscribe.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 18.06.15
 * Time: 16:54
 */

$this->params['showSubscribe'] = false;

$this->registerJsFile("//vk.com/js/api/openapi.js?116", ['position' => \yii\web\View::POS_HEAD]);

$this->registerJs(
    "
    // facebook

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = \"//connect.facebook.net/ru_RU/all.js#xfbml=1&appId=132147813635823\";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    var page_like_or_unlike_callback = function(url, html_element) {
      console.log(\"page_like_or_unlike_callback\");
      console.log(url);
    }

    // vk

    VK.init({apiId: 4278462, onlyWidgets: true});

    VK.Widgets.Group(\"vk_groups\", {
        mode: 0,
        width: \"300\",
        height: \"200\",
        color1: 'FFFFFF',
        color2: '2B587A',
        color3: '5B7FA6'
    }, 100926688);

"
);

$this->registerJs(
    "
    var page_like_or_unlike_callback = function(url, html_element) {
      console.log(\"page_like_or_unlike_callback\");
      console.log(url);
      //document.show_subscribe_form();
    }

    // In your onload handler
    FB.Event.subscribe('edge.create', page_like_or_unlike_callback);
    //FB.Event.subscribe('edge.remove', page_like_or_unlike_callback);

    VK.Observer.subscribe(\"widgets.groups.joined\", function f() {
        console.log(\"Thank you for your subscribe\");
        //document.show_subscribe_form();
    });

    ",
    \yii\web\View::POS_LOAD
);
?>
<div class="row">
    <div class="col-xs-12 margin-bottom-20">
        <div class="headline"><h2>Спасибо за подписку!</h2></div>
        <?php if (isset($model->profile->subscribeDoneText) && !empty($model->profile->subscribeDoneText)): ?>
            <?= $model->profile->subscribeDoneText ?>
        <?php else: ?>
            <p>Дорогой друг,</p>
            <p>Все получилось, твои данные успешно добавлены. <br>Проверь почту, инструкция отправлена на указанный
                электронный адрес.</p>
        <?php endif ?>
    </div>

    <div class="col-xs-12 text-center margin-bottom-20">
        <h3>Читай 5 сфер в социальных сетях</h3>
    </div>

    <div class="col-xs-12 col-sm-6 text-center margin-bottom-20">
        <div class="fb-page" data-href="https://www.facebook.com/5sfer" data-small-header="false"
             data-width="300" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"
             data-height="250">
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <div id="vk_groups"></div>
    </div>
    <div class="col-xs-12 text-center margin-top-20 margin-bottom-20">
        <h3 class="margin-top-20">Выбери что делать дальше</h3>
    </div>
    <div class="col-xs-12 text-center">
        <a class="btn-u btn-u-blue btn-u-lg rounded-2x margin-right-10" href="<?= \yii\helpers\Url::to('/', true) ?>">На
            главную</a>
    </div>

</div>